services:
  sun:
    image: darkobyte/cosmos_planet
    environment:
      SERVER_URL: ws://dev.gianluca.click:3001
      PLANET_ID: sun
      PLANET_NAME: COSMOS X
      PLANET_TYPE: star
      PLANET_PARENT: "none"
      PLANET_RADIUS: "0"
      PLANET_SPEED: "0"
      PLANET_ELEMENTS: dark_matter,fire
      PLANET_INFO: "The central star of our solar system. An unusual mixture of dark matter and fire."
      PLANET_SIZE: "4"
    restart: unless-stopped