services:
  mars:
    image: darkobyte/cosmos_planet
    environment:
      SERVER_URL: ws://cosmos.gianluca.click:3001
      PLANET_ID: mars
      PLANET_NAME: Mars
      PLANET_TYPE: star
      PLANET_PARENT: sun
      PLANET_RADIUS: "300"
      PLANET_SPEED: "0.005"
      PLANET_ELEMENTS: rock,iron
      PLANET_INFO: "4. Planet. Roter Planet wegen Eisenoxid."
      PLANET_SIZE: "2"
    restart: unless-stopped